#!/bin/bash
BASE=`dirname $0`

# Ensure that stow is installed
c=`brew list | grep stow 2>&1 > /dev/null`
if [[ "$?" != "0" ]]; then
  brew install stow
fi

ls -l $BASE | grep ^d | awk '{print $9}' | xargs stow -t ~ -d `dirname $0`
