# ~/.tmuxinator/trunk.yml
# you can make as many tabs as you wish...

project_name: default
project_root: /Volumes/Data/Users/local
pre: sudo ls /tmp
tabs:
  - Vim: vim
  - Pry: pry
  - bash:
  - bash:
  - bash:
  - bash:
  - bash:
  - bash:
  - bash:
  - Logs:
      layout: even-vertical
      panes:
        - top -u -s 3
        - sudo tail -f /var/log/system.log
